apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels:
    template: postgres-persistent-template
  name: postgresql
spec: 
  accessmode:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  

  
